import os
import sqlite3
from datetime import datetime, timedelta
from backend.config import load_config
import backend.database as db_module

class DigestGenerator:
    def __init__(self):
        self.config = load_config()
        self.digest_config = self.config.get("digest", {})
        self.min_score = self.digest_config.get("min_score_for_digest", 40)
        self.output_dir = os.path.abspath(os.path.join(
            os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 
            "digests"
        ))
        
    def generate_digest(self, hours_ago=24) -> str:
        """
        Generates a markdown digest of jobs matched in the last `hours_ago` hours.
        Saves the file to `output_dir` and returns the file path.
        """
        if not self.digest_config.get("enabled", True):
            return ""

        # Ensure directory exists
        os.makedirs(self.output_dir, exist_ok=True)

        # Connect to DB
        conn = sqlite3.connect(db_module.DB_PATH)
        conn.row_factory = sqlite3.Row
        cursor = conn.cursor()

        # Fetch jobs in the timeframe
        time_threshold = (datetime.now() - timedelta(hours=hours_ago)).isoformat()
        
        cursor.execute("""
            SELECT * FROM jobs 
            WHERE date_found >= ? AND match_score >= ? 
            ORDER BY match_score DESC, date_found DESC
        """, (time_threshold, self.min_score))
        
        rows = cursor.fetchall()
        conn.close()

        if not rows:
            return ""

        # Compile markdown
        now_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        file_timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"digest_{file_timestamp}.md"
        filepath = os.path.join(self.output_dir, filename)

        md = []
        md.append(f"# Job Search Digest - {now_str}")
        md.append(f"This digest contains jobs found and matched in the last {hours_ago} hours with a score of **{self.min_score}%** or higher.\n")
        md.append(f"**Total Matches**: {len(rows)}\n")
        md.append("| Score | Position | Company | Location | Source | Link |")
        md.append("| :--- | :--- | :--- | :--- | :--- | :--- |")

        for r in rows:
            # Format link markdown
            url = r["url"]
            link_str = f"[View Position]({url})" if url else "N/A"
            # Format score as strong if very high
            score = r["match_score"]
            score_str = f"**{score}%**" if score >= 75 else f"{score}%"
            
            # Escape pipes in markdown table
            title = r["title"].replace("|", "\\|")
            company = (r["company"] or "Unknown").replace("|", "\\|")
            loc = (r["location"] or "Remote").replace("|", "\\|")
            src = (r["source"] or "Unknown").replace("|", "\\|")

            md.append(f"| {score_str} | {title} | {company} | {loc} | {src} | {link_str} |")

        md.append("\n\n---\n*Generated by CareerRadar Job Search Automation Engine*")

        # Save to file
        with open(filepath, "w", encoding="utf-8") as f:
            f.write("\n".join(md))

        return filepath

    def list_digests(self) -> list[dict]:
        """
        Lists all generated digests with their file details.
        """
        if not os.path.exists(self.output_dir):
            return []
            
        digests = []
        for filename in sorted(os.listdir(self.output_dir), reverse=True):
            if filename.startswith("digest_") and filename.endswith(".md"):
                path = os.path.join(self.output_dir, filename)
                stat = os.stat(path)
                
                # Parse date from name
                try:
                    # digest_YYYYMMDD_HHMMSS.md
                    date_part = filename.replace("digest_", "").replace(".md", "")
                    dt = datetime.strptime(date_part, "%Y%m%d_%H%M%S")
                    formatted_date = dt.strftime("%B %d, %Y %I:%M %p")
                except:
                    formatted_date = "Unknown Date"
                    
                digests.append({
                    "filename": filename,
                    "date_created": formatted_date,
                    "size_bytes": stat.st_size
                })
        return digests

    def get_digest_content(self, filename: str) -> str:
        """
        Reads the raw content of a digest.
        """
        # Security check: prevent directory traversal
        clean_filename = os.path.basename(filename)
        path = os.path.join(self.output_dir, clean_filename)
        if not os.path.exists(path):
            return ""
            
        with open(path, "r", encoding="utf-8") as f:
            return f.read()
