import os
import sqlite3
from datetime import datetime, timedelta

import careerradar.core.database as db_module
from careerradar.core.config import load_config
from careerradar.core.paths import REPO_ROOT


class DigestGenerator:
    def __init__(self):
        self.config = load_config()
        self.digest_config = self.config.get("digest", {})
        # The digest is "jobs worth reading", so it selects on the judged verdict, not
        # on keyword coverage. `match_score >= 40` used to gate it and was printed as a
        # percent, which it never was -- the scale bottoms out around 15.
        self.max_tier = self.digest_config.get("max_tier", 4)
        self.output_dir = os.path.abspath(os.path.join(
            REPO_ROOT,
            "digests"
        ))

    def generate_digest(self, hours_ago=24) -> str:
        """
        Generates a markdown digest of jobs matched in the last `hours_ago` hours.
        Saves the file to `output_dir` and returns the file path.
        """
        if not self.digest_config.get("enabled", True):
            return ""

        # Ensure directory exists
        os.makedirs(self.output_dir, exist_ok=True)

        # Connect to DB
        conn = sqlite3.connect(db_module.DB_PATH)
        conn.row_factory = sqlite3.Row
        cursor = conn.cursor()

        # Fetch jobs in the timeframe
        time_threshold = (datetime.now() - timedelta(hours=hours_ago)).isoformat()

        cursor.execute("""
            SELECT j.*, v.eligibility, v.role_match, v.capability_match,
                   v.pareto_tier, v.role_summary
              FROM jobs j
              JOIN job_verdicts v
                ON v.job_id = j.id
               AND v.profile_version = (SELECT version FROM profiles WHERE is_active = 1)
              LEFT JOIN v_job_liveness l ON l.job_id = j.id
             WHERE j.date_found >= ?
               AND j.duplicate_of IS NULL
               AND v.eligibility = 'eligible'
               AND v.pareto_tier <= ?
               AND COALESCE(l.liveness, 'unknown') != 'likely_closed'
             ORDER BY v.pareto_tier ASC, j.date_found DESC
        """, (time_threshold, self.max_tier))

        rows = cursor.fetchall()
        conn.close()

        if not rows:
            return ""

        # Compile markdown
        now_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        file_timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"digest_{file_timestamp}.md"
        filepath = os.path.join(self.output_dir, filename)

        md = []
        md.append(f"# Job Search Digest - {now_str}")
        md.append(
            f"Jobs found in the last {hours_ago} hours that you are eligible for and that "
            f"rank in the top {self.max_tier} tiers. Tier 1 is the same role, done at a "
            f"higher level than asked; the tiers below trade off role match against "
            f"capability without one being ranked above the other.\n")
        md.append(f"**Total**: {len(rows)}\n")
        md.append("| Tier | Position | Company | What it is | Location | Link |")
        md.append("| :--- | :--- | :--- | :--- | :--- | :--- |")

        def cell(value, fallback=""):
            return (value or fallback).replace("|", "\\|")

        for r in rows:
            url = r["url"]
            link_str = f"[View Position]({url})" if url else "N/A"
            tier = r["pareto_tier"]
            tier_str = f"**{tier}**" if tier and tier <= 2 else str(tier or "-")
            md.append(
                f"| {tier_str} | {cell(r['title'])} | {cell(r['company'], 'Unknown')} "
                f"| {cell(r['role_summary'])} | {cell(r['location'], 'Remote')} "
                f"| {link_str} |")

        md.extend(self._skill_gap_section())
        md.append("\n\n---\n*Generated by CareerRadar Job Search Automation Engine*")

        # Save to file
        with open(filepath, "w", encoding="utf-8") as f:
            f.write("\n".join(md))

        return filepath


    def _skill_gap_section(self):
        """Top acquisition priorities, appended to each digest.

        Returns [] on any failure or when the corpus is too thin: a digest listing new
        postings is still useful without it, so this must never break generation.
        """
        try:
            from careerradar.core.config import load_config
            from careerradar.core.database import Database
            from careerradar.market.gap_analysis import GapAnalysis
            from careerradar.profile.adapter import load_profile
            from careerradar.taxonomy.roles import load_roles
            from careerradar.taxonomy.skills import load_taxonomy

            config = load_config()
            if not (config.get("digest") or {}).get("include_skill_gap", True):
                return []

            taxonomy = load_taxonomy()
            roles = load_roles()
            database = Database()
            try:
                result = GapAnalysis(
                    database, config, roles, taxonomy,
                    load_profile(taxonomy=taxonomy),
                ).analyse(window_days=90)
            finally:
                database.close()

            gaps = result["views"]["priority_gaps"][:8]
            if not gaps:
                return []

            md = ["\n\n## Skills worth acquiring next\n"]
            if result.get("weighting_fallback_reason"):
                md.append(f"*Caveat: {result['weighting_fallback_reason']}.*\n")
            provenance = result["provenance"]
            md.append(
                f"*Based on {provenance['n_postings']} postings "
                f"({provenance['n_good_fit']} of which you already match well).*\n"
            )
            md.append("| Skill | Priority | Blocking gap | Demand | Effort |")
            md.append("|---|---|---|---|---|")
            for row in gaps:
                md.append(
                    f"| {row['label']} | {row['priority']:.2f} "
                    f"| {row['blocking_gap'] * 100:.0f}% "
                    f"| {row['demand'] * 100:.0f}% | {row['effort']} |"
                )
            md.append(
                "\n*Blocking gap: the share of postings you otherwise match well that "
                "require this skill.*"
            )
            return md
        except Exception:  # noqa: BLE001 - a broken section must not sink the whole digest
            return []

    def list_digests(self) -> list[dict]:
        """
        Lists all generated digests with their file details.
        """
        if not os.path.exists(self.output_dir):
            return []

        digests = []
        for filename in sorted(os.listdir(self.output_dir), reverse=True):
            if filename.startswith("digest_") and filename.endswith(".md"):
                path = os.path.join(self.output_dir, filename)
                stat = os.stat(path)

                # Parse date from name
                try:
                    # digest_YYYYMMDD_HHMMSS.md
                    date_part = filename.replace("digest_", "").replace(".md", "")
                    dt = datetime.strptime(date_part, "%Y%m%d_%H%M%S")
                    formatted_date = dt.strftime("%B %d, %Y %I:%M %p")
                except ValueError:
                    formatted_date = "Unknown Date"

                digests.append({
                    "filename": filename,
                    "date_created": formatted_date,
                    "size_bytes": stat.st_size
                })
        return digests

    def get_digest_content(self, filename: str) -> str:
        """
        Reads the raw content of a digest.
        """
        # Security check: prevent directory traversal
        clean_filename = os.path.basename(filename)
        path = os.path.join(self.output_dir, clean_filename)
        if not os.path.exists(path):
            return ""

        with open(path, encoding="utf-8") as f:
            return f.read()
