// Digest rendering. Replaces the hand-rolled, inline-styled converter in
// `frontend/js/lib/markdown.js` -- that version handled only headers, bold, links and
// tables, and baked presentation into inline `style="..."` strings because it predated
// having a bundler. `marked` is a real CommonMark implementation and costs one dependency.
//
// Digest content is generated by this app's own pipeline (`careerradar.market.digest`), not
// supplied by another user, so `marked`'s default raw-HTML passthrough is an acceptable risk
// for a single-owner dashboard -- the same trust boundary the rest of this app draws around
// its own generated content.
import { marked } from "marked";

marked.setOptions({ breaks: false, gfm: true });

export function renderMarkdown(md: string | null | undefined): string {
  if (!md) return "";
  return marked.parse(md, { async: false });
}
